icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#aaaaaa"
info_bg = "#000000"
info_fg = "#bbbbbb"
good_bg = "#000000"
good_fg = "#cccccc"
warning_bg = "#000000"
warning_fg = "#eeeeee"
critical_bg = "#000000"
critical_fg = "#ffffff"
separator = "\ue0b2"
alternating_tint_bg = "#111111"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome4"

[icons.overrides]
# emacs = ""
backlight = "\uf0eb"
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "\uf240"

# [[block]]
# block = "custom"
# command = "echo '{\"icon\":\"emacs\"}'"
# json = true

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play |} "
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "custom"
command = "tail -f /run/user/1000/statusbar.fifo"
format = "{ $text |}"
hide_when_empty = true
persistent = true

[[block]]
block = "memory"
format = " $icon  $mem_used.eng(w:4)/$mem_total.eng(w:4) "
# format = " $icon $mem_total_used.eng(w:4)/$mem_total.eng(w:4) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
format = " $icon  $barchart $utilization "
format_alt = " $icon  $barchart $frequency{ $boost|} "
interval = 3
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "battery"
format = " $icon  $percentage "
full_format = " $icon  "
not_charging_format = " $icon  "
driver = "upower"
missing_format = ""

# [[block]]
# block = "net"
# format = " $icon $device "
# interval = 3
# device = "^wlan0$"

[[block]]
block = "backlight"
device = "amdgpu_bl1"
invert_icons = true

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

# [[block]]
# block = "notify"
# format = " $icon {($notification_count.eng(w:1)) |}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
