#!/usr/bin/env sh

prompt(){
EWW_BIN="/usr/bin/env eww"

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    ${EWW_BIN} daemon
    sleep 1
fi
}

if [ "$1" = "off" ]; then
  systemctl poweroff
elif [ "$1" = "suspend" ]; then
  systemctl suspend
elif [ "$1" = "logout" ]; then
  hyprctl dispatch exit
elif [ "$1" = "reboot" ]; then
  systemctl reboot
elif [ "$1" = "wmrestart" ]; then
  hyprctl reload
fi
